create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_user_id_created_at_idx
  on public.chat_messages (user_id, created_at desc);

create table if not exists public.user_state (
  user_id bigint primary key,
  department text,
  last_report_type text,
  last_days integer,
  updated_at timestamptz not null default now()
);
